"""Initial schema with erasure queue and indexes

Revision ID: 5f1623dbfc18
Revises: 
Create Date: 2026-06-09 12:43:32.049177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f1623dbfc18'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('app_config',
    sa.Column('config_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('config_id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('asha_training_modules',
    sa.Column('module_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('module_id')
    )
    op.create_table('audit_logs',
    sa.Column('log_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('record_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('log_id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('idx_audit_action', ['action'], unique=False)
        batch_op.create_index('idx_audit_timestamp', ['timestamp'], unique=False)

    op.create_table('devices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=100), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('owner_type', sa.String(length=20), nullable=False),
    sa.Column('platform', sa.String(length=10), nullable=False),
    sa.Column('registered_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('fcm_token', sa.String(length=512), nullable=True),
    sa.CheckConstraint("owner_type IN ('patient','asha_worker')", name='ck_device_owner_type'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id')
    )
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_devices_owner_id'), ['owner_id'], unique=False)

    op.create_table('notification_preferences',
    sa.Column('pref_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('sms_enabled', sa.Boolean(), nullable=True),
    sa.Column('email_enabled', sa.Boolean(), nullable=True),
    sa.Column('push_enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('pref_id')
    )
    op.create_table('notifications',
    sa.Column('notification_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_table('research_exports',
    sa.Column('export_id', sa.UUID(), nullable=False),
    sa.Column('exported_by', sa.UUID(), nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('k_anonymity_verified', sa.Boolean(), nullable=True),
    sa.Column('export_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('k_anonymity_verified = true', name='check_k_anonymity_verified'),
    sa.PrimaryKeyConstraint('export_id')
    )
    op.create_table('subscription_tiers',
    sa.Column('tier_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('features', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('tier_name', sa.String(length=50), nullable=True),
    sa.Column('price_monthly_rs', sa.Float(), nullable=True),
    sa.Column('price_annual_rs', sa.Float(), nullable=True),
    sa.Column('wound_sessions_per_month', sa.Integer(), nullable=True),
    sa.Column('skin_sessions_per_month', sa.Integer(), nullable=True),
    sa.Column('contributing_factor_sessions_per_quarter', sa.Integer(), nullable=True),
    sa.Column('teleconsult_included_per_month', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('tier_id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('hashed_password', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('device_id', sa.String(length=120), nullable=True),
    sa.Column('fcm_token', sa.String(length=512), nullable=True),
    sa.Column('preferred_language', sa.String(length=5), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_phone_number'), ['phone_number'], unique=True)

    op.create_table('asha_workers',
    sa.Column('worker_id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('pin_hash', sa.String(length=128), nullable=False),
    sa.Column('village', sa.String(length=255), nullable=True),
    sa.Column('district', sa.String(length=255), nullable=False),
    sa.Column('phc_name', sa.String(length=200), nullable=True),
    sa.Column('block_name', sa.String(length=120), nullable=True),
    sa.Column('villages_covered', sa.Text(), nullable=True),
    sa.Column('training_completed', sa.Boolean(), nullable=True),
    sa.Column('training_completed_at', sa.DateTime(), nullable=True),
    sa.Column('training_score', sa.Float(), nullable=True),
    sa.Column('supervisor_name', sa.String(length=120), nullable=True),
    sa.Column('supervisor_phone', sa.String(length=15), nullable=True),
    sa.Column('bank_account_encrypted', sa.Text(), nullable=True),
    sa.Column('bank_ifsc', sa.String(length=20), nullable=True),
    sa.Column('state', sa.String(length=80), nullable=True),
    sa.Column('device_id', sa.String(length=100), nullable=True),
    sa.Column('asha_id_number', sa.String(length=40), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('commission_balance', sa.Float(), nullable=False),
    sa.Column('total_screenings', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('worker_id'),
    sa.UniqueConstraint('asha_id_number')
    )
    with op.batch_alter_table('asha_workers', schema=None) as batch_op:
        batch_op.create_index('idx_asha_district', ['district'], unique=False)

    op.create_table('doctors',
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=True),
    sa.Column('nmc_number', sa.String(length=50), nullable=False),
    sa.Column('specialisation', sa.String(length=100), nullable=False),
    sa.Column('languages', sa.String(length=255), nullable=False),
    sa.Column('fee_per_consult', sa.Float(), nullable=False),
    sa.Column('hospital_name', sa.String(length=200), nullable=True),
    sa.Column('hospital_department', sa.String(length=120), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('doctor_id')
    )
    op.create_table('asha_commissions',
    sa.Column('commission_id', sa.UUID(), nullable=False),
    sa.Column('asha_worker_id', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('period', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asha_worker_id'], ['asha_workers.worker_id'], ),
    sa.PrimaryKeyConstraint('commission_id')
    )
    with op.batch_alter_table('asha_commissions', schema=None) as batch_op:
        batch_op.create_index('idx_commission_worker', ['asha_worker_id'], unique=False)

    op.create_table('patients',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('village', sa.String(length=255), nullable=True),
    sa.Column('district', sa.String(length=255), nullable=False),
    sa.Column('block', sa.String(length=255), nullable=True),
    sa.Column('pin_code', sa.String(length=20), nullable=True),
    sa.Column('state', sa.String(length=80), nullable=True),
    sa.Column('date_of_birth', sa.String(length=32), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=120), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=15), nullable=True),
    sa.Column('preferred_language', sa.String(length=5), nullable=True),
    sa.Column('password_hash', sa.String(length=200), nullable=True),
    sa.Column('is_research_participant', sa.Boolean(), nullable=True),
    sa.Column('is_commercial_subscriber', sa.Boolean(), nullable=True),
    sa.Column('created_by_asha_id', sa.String(length=50), nullable=True),
    sa.Column('research_enrolled_at', sa.DateTime(), nullable=True),
    sa.Column('known_conditions', sa.Text(), nullable=True),
    sa.Column('allergies', sa.Text(), nullable=True),
    sa.Column('aadhar_id', sa.String(length=12), nullable=True),
    sa.Column('consent_given_at', sa.DateTime(), nullable=True),
    sa.Column('consent_version', sa.Integer(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_asha_id'], ['asha_workers.worker_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('patient_id')
    )
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.create_index('idx_patient_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_patient_district', ['district'], unique=False)

    op.create_table('asha_patient_assignments',
    sa.Column('assignment_id', sa.UUID(), nullable=False),
    sa.Column('asha_worker_id', sa.String(length=50), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asha_worker_id'], ['asha_workers.worker_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.PrimaryKeyConstraint('assignment_id')
    )
    with op.batch_alter_table('asha_patient_assignments', schema=None) as batch_op:
        batch_op.create_index('idx_asha_assignment', ['asha_worker_id', 'patient_id'], unique=False)

    op.create_table('consents',
    sa.Column('consent_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('consent_version', sa.String(length=50), nullable=True),
    sa.Column('data_use_category', sa.String(length=100), nullable=True),
    sa.Column('given_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('consent_type', sa.String(length=50), nullable=True),
    sa.Column('signed_at', sa.DateTime(), nullable=True),
    sa.Column('signed_by_method', sa.String(length=50), nullable=True),
    sa.Column('modules_consented', sa.Text(), nullable=True),
    sa.Column('digital_signature_hash', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.PrimaryKeyConstraint('consent_id')
    )
    op.create_table('doctor_patient_assignments',
    sa.Column('assignment_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.doctor_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.PrimaryKeyConstraint('assignment_id')
    )
    op.create_table('erasure_queue',
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.PrimaryKeyConstraint('request_id')
    )
    with op.batch_alter_table('erasure_queue', schema=None) as batch_op:
        batch_op.create_index('idx_erasure_queue_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_erasure_queue_patient', ['patient_id'], unique=False)
        batch_op.create_index('idx_erasure_queue_status', ['status'], unique=False)

    op.create_table('patient_medical_history',
    sa.Column('history_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('hba1c', sa.Float(), nullable=True),
    sa.Column('diabetes_duration_years', sa.Integer(), nullable=True),
    sa.Column('blood_pressure', sa.String(length=50), nullable=True),
    sa.Column('prior_foot_problems', sa.Text(), nullable=True),
    sa.Column('current_medications', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.Column('diabetes_type', sa.String(length=50), nullable=True),
    sa.Column('hba1c_date', sa.String(length=50), nullable=True),
    sa.Column('has_hypertension', sa.Boolean(), nullable=True),
    sa.Column('has_ckd', sa.Boolean(), nullable=True),
    sa.Column('has_cad', sa.Boolean(), nullable=True),
    sa.Column('previous_dfu', sa.Boolean(), nullable=True),
    sa.Column('smoking_status', sa.String(length=50), nullable=True),
    sa.Column('bmi', sa.Float(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('bp_systolic', sa.Integer(), nullable=True),
    sa.Column('bp_diastolic', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.PrimaryKeyConstraint('history_id')
    )
    with op.batch_alter_table('patient_medical_history', schema=None) as batch_op:
        batch_op.create_index('idx_med_history_patient', ['patient_id'], unique=False)

    op.create_table('payment_transactions',
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('transaction_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('subscription_id', sa.String(length=36), nullable=True),
    sa.Column('transaction_type', sa.String(length=50), nullable=True),
    sa.Column('amount_rs', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('razorpay_payment_id', sa.String(length=100), nullable=True),
    sa.Column('razorpay_order_id', sa.String(length=100), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    with op.batch_alter_table('payment_transactions', schema=None) as batch_op:
        batch_op.create_index('idx_transaction_patient', ['patient_id'], unique=False)

    op.create_table('screenings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('asha_id', sa.String(length=50), nullable=True),
    sa.Column('condition_type', sa.String(length=10), nullable=False),
    sa.Column('risk_level', sa.String(length=10), nullable=False),
    sa.Column('ai_result', sa.Text(), nullable=True),
    sa.Column('model_source', sa.String(length=30), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('photo_data', sa.Text(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('consent_timestamp', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("condition_type IN ('skin','eye','wound')", name='ck_screening_condition'),
    sa.CheckConstraint("risk_level IN ('low','medium','high')", name='ck_screening_risk'),
    sa.ForeignKeyConstraint(['asha_id'], ['asha_workers.worker_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('screenings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_screenings_asha_id'), ['asha_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_screenings_patient_id'), ['patient_id'], unique=False)

    op.create_table('subscriptions',
    sa.Column('subscription_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('tier_id', sa.UUID(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('trial_ends_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('amount_rs', sa.Float(), nullable=True),
    sa.Column('auto_renew', sa.Boolean(), nullable=True),
    sa.Column('current_period_start', sa.DateTime(), nullable=True),
    sa.Column('current_period_end', sa.DateTime(), nullable=True),
    sa.Column('next_billing_date', sa.DateTime(), nullable=True),
    sa.Column('grace_period_ends_at', sa.DateTime(), nullable=True),
    sa.Column('paused_at', sa.DateTime(), nullable=True),
    sa.Column('pause_ends_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.ForeignKeyConstraint(['tier_id'], ['subscription_tiers.tier_id'], ),
    sa.PrimaryKeyConstraint('subscription_id')
    )
    op.create_table('teleconsult_requests',
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('assigned_doctor_id', sa.UUID(), nullable=True),
    sa.Column('requested_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('alert_id', sa.String(length=36), nullable=True),
    sa.Column('request_type', sa.String(length=20), nullable=True),
    sa.Column('patient_concern_en', sa.Text(), nullable=True),
    sa.Column('patient_concern_bn', sa.Text(), nullable=True),
    sa.Column('preferred_callback_time', sa.String(length=64), nullable=True),
    sa.Column('estimated_callback_at', sa.DateTime(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('actual_call_at', sa.DateTime(), nullable=True),
    sa.Column('call_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('doctor_notes', sa.Text(), nullable=True),
    sa.Column('patient_rating', sa.Integer(), nullable=True),
    sa.Column('patient_feedback', sa.Text(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('prescription_json', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['assigned_doctor_id'], ['doctors.doctor_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.PrimaryKeyConstraint('request_id')
    )
    with op.batch_alter_table('teleconsult_requests', schema=None) as batch_op:
        batch_op.create_index('idx_teleconsult_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_teleconsult_patient', ['patient_id'], unique=False)

    op.create_table('wound_sites',
    sa.Column('wound_site_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('location_code', sa.String(length=50), nullable=True),
    sa.Column('initial_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('foot_side', sa.String(length=20), nullable=True),
    sa.Column('location_on_foot', sa.String(length=100), nullable=True),
    sa.Column('toe_number', sa.Integer(), nullable=True),
    sa.Column('first_detected_date', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('current_wagner_grade', sa.Integer(), nullable=True),
    sa.Column('is_primary_site', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('last_session_at', sa.DateTime(), nullable=True),
    sa.Column('total_sessions', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.PrimaryKeyConstraint('wound_site_id')
    )
    with op.batch_alter_table('wound_sites', schema=None) as batch_op:
        batch_op.create_index('idx_wound_site_patient', ['patient_id'], unique=False)

    op.create_table('commissions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('asha_id', sa.String(length=50), nullable=False),
    sa.Column('screening_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('commission_type', sa.String(length=20), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("commission_type IN ('screening','referral')", name='ck_commission_type'),
    sa.ForeignKeyConstraint(['asha_id'], ['asha_workers.worker_id'], ),
    sa.ForeignKeyConstraint(['screening_id'], ['screenings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('commissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_commissions_asha_id'), ['asha_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_commissions_screening_id'), ['screening_id'], unique=False)

    op.create_table('consultations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('screening_id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=True),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('time_slot', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('queue_position', sa.Integer(), nullable=True),
    sa.Column('fee_amount', sa.Float(), nullable=False),
    sa.Column('payment_status', sa.String(length=20), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("mode IN ('async','scheduled','instant')", name='ck_consultation_mode'),
    sa.CheckConstraint("status IN ('pending','assigned','in_progress','completed','cancelled')", name='ck_consultation_status'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.doctor_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.ForeignKeyConstraint(['screening_id'], ['screenings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('consultations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consultations_doctor_id'), ['doctor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_consultations_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_consultations_screening_id'), ['screening_id'], unique=True)

    op.create_table('monitoring_sessions',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('wound_site_id', sa.UUID(), nullable=False),
    sa.Column('session_date', sa.DateTime(), nullable=False),
    sa.Column('asha_worker_id', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('session_type', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['asha_worker_id'], ['asha_workers.worker_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.ForeignKeyConstraint(['wound_site_id'], ['wound_sites.wound_site_id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    with op.batch_alter_table('monitoring_sessions', schema=None) as batch_op:
        batch_op.create_index('idx_session_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_session_date', ['session_date'], unique=False)
        batch_op.create_index('idx_session_patient', ['patient_id'], unique=False)

    op.create_table('session_schedule',
    sa.Column('schedule_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('asha_worker_id', sa.String(length=50), nullable=True),
    sa.Column('scheduled_date', sa.DateTime(), nullable=False),
    sa.Column('reminder_sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('wound_site_id', sa.UUID(), nullable=True),
    sa.Column('session_type', sa.String(length=50), nullable=True),
    sa.Column('due_by_date', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['asha_worker_id'], ['asha_workers.worker_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.ForeignKeyConstraint(['wound_site_id'], ['wound_sites.wound_site_id'], ),
    sa.PrimaryKeyConstraint('schedule_id')
    )
    op.create_table('ai_results',
    sa.Column('result_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('wagner_grade', sa.Integer(), nullable=True),
    sa.Column('tissue_type', sa.String(length=50), nullable=True),
    sa.Column('infection_probability', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('processing_method', sa.String(length=30), nullable=True),
    sa.Column('overall_confidence', sa.Float(), nullable=True),
    sa.Column('wound_area_cm2', sa.Float(), nullable=True),
    sa.Column('alert_level', sa.String(length=10), nullable=True),
    sa.Column('details_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['monitoring_sessions.session_id'], ),
    sa.PrimaryKeyConstraint('result_id')
    )
    with op.batch_alter_table('ai_results', schema=None) as batch_op:
        batch_op.create_index('idx_ai_result_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_ai_result_patient', ['patient_id'], unique=False)
        batch_op.create_index('idx_ai_result_session', ['session_id'], unique=False)

    op.create_table('alerts',
    sa.Column('alert_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('wound_site_id', sa.UUID(), nullable=True),
    sa.Column('alert_level', sa.String(length=10), nullable=True),
    sa.Column('alert_type', sa.String(length=60), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('message_patient_en', sa.Text(), nullable=True),
    sa.Column('message_patient_bn', sa.Text(), nullable=True),
    sa.Column('message_doctor_en', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('acknowledgement_note', sa.Text(), nullable=True),
    sa.Column('escalation_level', sa.Integer(), nullable=True),
    sa.Column('escalation_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['monitoring_sessions.session_id'], ),
    sa.ForeignKeyConstraint(['wound_site_id'], ['wound_sites.wound_site_id'], ),
    sa.PrimaryKeyConstraint('alert_id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index('idx_alert_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_alert_patient', ['patient_id'], unique=False)

    op.create_table('clinical_notes',
    sa.Column('note_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('doctor_id', sa.UUID(), nullable=True),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('wound_locations', sa.JSON(), nullable=True),
    sa.Column('infection_signs', sa.JSON(), nullable=True),
    sa.Column('treatment_recommendations', sa.JSON(), nullable=True),
    sa.Column('extracted_at', sa.DateTime(), nullable=True),
    sa.Column('nlp_model_version', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.doctor_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['monitoring_sessions.session_id'], ),
    sa.PrimaryKeyConstraint('note_id')
    )
    with op.batch_alter_table('clinical_notes', schema=None) as batch_op:
        batch_op.create_index('idx_clinical_note_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_clinical_note_patient', ['patient_id'], unique=False)
        batch_op.create_index('idx_clinical_note_session', ['session_id'], unique=False)

    op.create_table('multimodal_analyses',
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('hba1c', sa.Float(), nullable=False),
    sa.Column('diabetes_duration_years', sa.Integer(), nullable=False),
    sa.Column('systolic_bp', sa.Integer(), nullable=False),
    sa.Column('diastolic_bp', sa.Integer(), nullable=False),
    sa.Column('severity_grade', sa.Integer(), nullable=False),
    sa.Column('severity_label', sa.String(length=255), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('tissue_assessment', sa.Text(), nullable=False),
    sa.Column('infection_risk', sa.String(length=50), nullable=False),
    sa.Column('healing_prognosis', sa.String(length=50), nullable=False),
    sa.Column('clinical_insights', sa.JSON(), nullable=True),
    sa.Column('risk_factors', sa.JSON(), nullable=True),
    sa.Column('immediate_actions', sa.JSON(), nullable=True),
    sa.Column('follow_up_days', sa.Integer(), nullable=False),
    sa.Column('specialist_referral', sa.Boolean(), nullable=False),
    sa.Column('raw_response', sa.Text(), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['monitoring_sessions.session_id'], ),
    sa.PrimaryKeyConstraint('analysis_id')
    )
    with op.batch_alter_table('multimodal_analyses', schema=None) as batch_op:
        batch_op.create_index('idx_multimodal_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_multimodal_patient', ['patient_id'], unique=False)
        batch_op.create_index('idx_multimodal_session', ['session_id'], unique=False)

    op.create_table('photographs',
    sa.Column('photo_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('encrypted', sa.Boolean(), nullable=False),
    sa.Column('taken_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('encrypted = true', name='check_photos_encrypted'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['monitoring_sessions.session_id'], ),
    sa.PrimaryKeyConstraint('photo_id')
    )
    with op.batch_alter_table('photographs', schema=None) as batch_op:
        batch_op.create_index('idx_photo_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_photo_patient', ['patient_id'], unique=False)
        batch_op.create_index('idx_photo_session', ['session_id'], unique=False)

    op.create_table('prescriptions',
    sa.Column('prescription_id', sa.UUID(), nullable=False),
    sa.Column('consultation_id', sa.String(length=36), nullable=True),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('medicine', sa.String(length=255), nullable=True),
    sa.Column('dosage', sa.String(length=100), nullable=True),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('diagnosis', sa.String(length=200), nullable=True),
    sa.Column('icd10_code', sa.String(length=20), nullable=True),
    sa.Column('medications', sa.Text(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('follow_up_days', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.doctor_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.PrimaryKeyConstraint('prescription_id'),
    sa.UniqueConstraint('consultation_id')
    )
    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.create_index('idx_prescription_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_prescription_patient', ['patient_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.drop_index('idx_prescription_patient')
        batch_op.drop_index('idx_prescription_created_at')

    op.drop_table('prescriptions')
    with op.batch_alter_table('photographs', schema=None) as batch_op:
        batch_op.drop_index('idx_photo_session')
        batch_op.drop_index('idx_photo_patient')
        batch_op.drop_index('idx_photo_created_at')

    op.drop_table('photographs')
    with op.batch_alter_table('multimodal_analyses', schema=None) as batch_op:
        batch_op.drop_index('idx_multimodal_session')
        batch_op.drop_index('idx_multimodal_patient')
        batch_op.drop_index('idx_multimodal_created_at')

    op.drop_table('multimodal_analyses')
    with op.batch_alter_table('clinical_notes', schema=None) as batch_op:
        batch_op.drop_index('idx_clinical_note_session')
        batch_op.drop_index('idx_clinical_note_patient')
        batch_op.drop_index('idx_clinical_note_created_at')

    op.drop_table('clinical_notes')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index('idx_alert_patient')
        batch_op.drop_index('idx_alert_created_at')

    op.drop_table('alerts')
    with op.batch_alter_table('ai_results', schema=None) as batch_op:
        batch_op.drop_index('idx_ai_result_session')
        batch_op.drop_index('idx_ai_result_patient')
        batch_op.drop_index('idx_ai_result_created_at')

    op.drop_table('ai_results')
    op.drop_table('session_schedule')
    with op.batch_alter_table('monitoring_sessions', schema=None) as batch_op:
        batch_op.drop_index('idx_session_patient')
        batch_op.drop_index('idx_session_date')
        batch_op.drop_index('idx_session_created_at')

    op.drop_table('monitoring_sessions')
    with op.batch_alter_table('consultations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consultations_screening_id'))
        batch_op.drop_index(batch_op.f('ix_consultations_patient_id'))
        batch_op.drop_index(batch_op.f('ix_consultations_doctor_id'))

    op.drop_table('consultations')
    with op.batch_alter_table('commissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_commissions_screening_id'))
        batch_op.drop_index(batch_op.f('ix_commissions_asha_id'))

    op.drop_table('commissions')
    with op.batch_alter_table('wound_sites', schema=None) as batch_op:
        batch_op.drop_index('idx_wound_site_patient')

    op.drop_table('wound_sites')
    with op.batch_alter_table('teleconsult_requests', schema=None) as batch_op:
        batch_op.drop_index('idx_teleconsult_patient')
        batch_op.drop_index('idx_teleconsult_created_at')

    op.drop_table('teleconsult_requests')
    op.drop_table('subscriptions')
    with op.batch_alter_table('screenings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_screenings_patient_id'))
        batch_op.drop_index(batch_op.f('ix_screenings_asha_id'))

    op.drop_table('screenings')
    with op.batch_alter_table('payment_transactions', schema=None) as batch_op:
        batch_op.drop_index('idx_transaction_patient')

    op.drop_table('payment_transactions')
    with op.batch_alter_table('patient_medical_history', schema=None) as batch_op:
        batch_op.drop_index('idx_med_history_patient')

    op.drop_table('patient_medical_history')
    with op.batch_alter_table('erasure_queue', schema=None) as batch_op:
        batch_op.drop_index('idx_erasure_queue_status')
        batch_op.drop_index('idx_erasure_queue_patient')
        batch_op.drop_index('idx_erasure_queue_created_at')

    op.drop_table('erasure_queue')
    op.drop_table('doctor_patient_assignments')
    op.drop_table('consents')
    with op.batch_alter_table('asha_patient_assignments', schema=None) as batch_op:
        batch_op.drop_index('idx_asha_assignment')

    op.drop_table('asha_patient_assignments')
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_index('idx_patient_district')
        batch_op.drop_index('idx_patient_created_at')

    op.drop_table('patients')
    with op.batch_alter_table('asha_commissions', schema=None) as batch_op:
        batch_op.drop_index('idx_commission_worker')

    op.drop_table('asha_commissions')
    op.drop_table('doctors')
    with op.batch_alter_table('asha_workers', schema=None) as batch_op:
        batch_op.drop_index('idx_asha_district')

    op.drop_table('asha_workers')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_phone_number'))

    op.drop_table('users')
    op.drop_table('subscription_tiers')
    op.drop_table('research_exports')
    op.drop_table('notifications')
    op.drop_table('notification_preferences')
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_devices_owner_id'))

    op.drop_table('devices')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('idx_audit_timestamp')
        batch_op.drop_index('idx_audit_action')

    op.drop_table('audit_logs')
    op.drop_table('asha_training_modules')
    op.drop_table('app_config')
    op.drop_table('admins')
    # ### end Alembic commands ###
